//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pocketgym.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserWorkout
    {
        public int WorkoutID { get; set; }
        public System.DateTime DateCompleted { get; set; }
        public Nullable<int> ExerciseID { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual Exercis Exercis { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
